fix(deps): update dependency pywebview to v6.1 (#218)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [pywebview](https://redirect.github.com/r0x0r/pywebview) | `==6.0` ->
`==6.1` |
[![age](https://developer.mend.io/api/mc/badges/age/pypi/pywebview/6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/pypi/pywebview/6.0/6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>r0x0r/pywebview (pywebview)</summary>

###
[`v6.1`](https://redirect.github.com/r0x0r/pywebview/releases/tag/6.1)

[Compare
Source](https://redirect.github.com/r0x0r/pywebview/compare/6.0...6.1)

##### ⚡ Features

- `All` New \`webview\.settings\['DRAG\_REGION\_DIRECT\_TARGET\_ONLY']
setting to control whether drag region selector matches only direct
targets or any element in the event path. Default is False. Thanks
[@&#8203;chrissantamaria](https://redirect.github.com/chrissantamaria)
- `EdgeChromium` Ability to bundle WebView2 runtime with the application
via `webview.settings['WEBVIEW2_RUNTIME_PATH']`. Thanks
[@&#8203;leovuk](https://redirect.github.com/leovuk)
- `Cocoa` Support for application menu. Thanks
[@&#8203;camdarley](https://redirect.github.com/camdarley).
[#&#8203;1725](https://redirect.github.com/r0x0r/pywebview/issues/1725)

##### 🚀 Improvements

- `All` Handle new elements in draggable and drag region client logic.
Thanks
[@&#8203;chrissantamaria](https://redirect.github.com/chrissantamaria)
- `All` Improve detection of cyclic structures during serialization from
JS to Python.
[#&#8203;1708](https://redirect.github.com/r0x0r/pywebview/issues/1708)
- `QT` Properly handle SIGINT to quit program allowing to close the
window with Ctrl+C in terminal. Thanks
[@&#8203;chrissantamaria](https://redirect.github.com/chrissantamaria).
- `Cocoa` Add support for 'New Folder' button in FOLDER\_DIALOG on
macOS. Thanks
[@&#8203;camdarley](https://redirect.github.com/camdarley).
[#&#8203;1710](https://redirect.github.com/r0x0r/pywebview/issues/1710)
- `Dev` Automatic linting and formatting on pre-commit hook
installation.

##### 🐞 Bug fixes

- `All` Fix state change event not being fired on state change from JS
side
[#&#8203;1698](https://redirect.github.com/r0x0r/pywebview/issues/1698)
- `All` Fix state values with special characters not being set properly.
- `All` Fix special characters handling in HTML attributes and styles in
`Element` object.
- `Android` Fix `window.event.closed` not being fired
- `Android` Improve cleanup on application exit
- `Cocoa` Support for partial functions in menu actions
[#&#8203;1707](https://redirect.github.com/r0x0r/pywebview/issues/1707)
- `Cocoa` Add missing pyobjc-framework-UniformTypeIdentifiers
dependency. Thanks
[@&#8203;Josef-Haupt](https://redirect.github.com/Josef-Haupt).
- `Cocoa` module 'objc.\_objc' has no attribute '**file**' after package
[#&#8203;1717](https://redirect.github.com/r0x0r/pywebview/issues/1717)
- `GTK` Fix data not being remove on application quit in private mode
[#&#8203;1713](https://redirect.github.com/r0x0r/pywebview/issues/1713)
- `Winforms` AttributeError: 'Screen' object has no attribute 'X
[#&#8203;1704](https://redirect.github.com/r0x0r/pywebview/issues/1704)
- `MSHTML` Fix MSTML compatibility
[#&#8203;1701](https://redirect.github.com/r0x0r/pywebview/issues/1701)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/jan-mue/pycodium).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xNTkuNCIsInVwZGF0ZWRJblZlciI6IjQxLjE1OS40IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJkZXBlbmRlbmNpZXMiXX0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>