fix(deps): update dependency psutil to v7.2.2 (#368)
This PR contains the following updates:

| Package | Change |
[Age](https://docs.renovatebot.com/merge-confidence/) |
[Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
| [psutil](https://redirect.github.com/giampaolo/psutil) | `==7.2.1` →
`==7.2.2` |
![age](https://developer.mend.io/api/mc/badges/age/pypi/psutil/7.2.2?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/pypi/psutil/7.2.1/7.2.2?slim=true)
|

---

### Release Notes

<details>
<summary>giampaolo/psutil (psutil)</summary>

###
[`v7.2.2`](https://redirect.github.com/giampaolo/psutil/blob/HEAD/HISTORY.rst#722)

[Compare
Source](https://redirect.github.com/giampaolo/psutil/compare/release-7.2.1...release-7.2.2)

\=====

2026-01-28

**Enhancements**

- 2705\_: \[Linux]: `Process.wait()`\_ now uses `pidfd_open()` +
`poll()` for
  waiting, resulting in no busy loop and faster response times. Requires
  Linux >= 5.3 and Python >= 3.9. Falls back to traditional polling if
  unavailable.
- 2705\_: \[macOS], \[BSD]: `Process.wait()`\_ now uses `kqueue()` for
waiting,
  resulting in no busy loop and faster response times.

**Bug fixes**

- 2701\_, \[macOS]: fix compilation error on macOS < 10.7. (patch by
Sergey
  Fedorov)
- 2707\_, \[macOS]: fix potential memory leaks in error paths of
  `Process.memory_full_info()` and `Process.threads()`.
- 2708\_, \[macOS]: Process.cmdline()`_ and `Process.environ()`_ may
fail with ``OSError: [Errno 0] Undefined error`` (from
``sysctl(KERN_PROCARGS2)``).
  They now raise `AccessDenied\`\_ instead.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/jan-mue/pycodium).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0Mi45NS4yIiwidXBkYXRlZEluVmVyIjoiNDIuOTUuMiIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiZGVwZW5kZW5jaWVzIl19-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>